/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TownhallRouteImport } from './routes/townhall'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QaCoachingRouteImport } from './routes/qa-coaching'
import { Route as PerformanceIntelligenceRouteImport } from './routes/performance-intelligence'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MemosRouteImport } from './routes/memos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeHubIndexRouteImport } from './routes/knowledge-hub.index'
import { Route as KnowledgeHubSopIdRouteImport } from './routes/knowledge-hub.$sopId'

const TownhallRoute = TownhallRouteImport.update({
  id: '/townhall',
  path: '/townhall',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QaCoachingRoute = QaCoachingRouteImport.update({
  id: '/qa-coaching',
  path: '/qa-coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceIntelligenceRoute = PerformanceIntelligenceRouteImport.update({
  id: '/performance-intelligence',
  path: '/performance-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MemosRoute = MemosRouteImport.update({
  id: '/memos',
  path: '/memos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeHubIndexRoute = KnowledgeHubIndexRouteImport.update({
  id: '/knowledge-hub/',
  path: '/knowledge-hub/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeHubSopIdRoute = KnowledgeHubSopIdRouteImport.update({
  id: '/knowledge-hub/$sopId',
  path: '/knowledge-hub/$sopId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/administration': typeof AdministrationRoute
  '/analytics': typeof AnalyticsRoute
  '/assessments': typeof AssessmentsRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/memos': typeof MemosRoute
  '/notifications': typeof NotificationsRoute
  '/performance-intelligence': typeof PerformanceIntelligenceRoute
  '/qa-coaching': typeof QaCoachingRoute
  '/settings': typeof SettingsRoute
  '/townhall': typeof TownhallRoute
  '/knowledge-hub/$sopId': typeof KnowledgeHubSopIdRoute
  '/knowledge-hub/': typeof KnowledgeHubIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/administration': typeof AdministrationRoute
  '/analytics': typeof AnalyticsRoute
  '/assessments': typeof AssessmentsRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/memos': typeof MemosRoute
  '/notifications': typeof NotificationsRoute
  '/performance-intelligence': typeof PerformanceIntelligenceRoute
  '/qa-coaching': typeof QaCoachingRoute
  '/settings': typeof SettingsRoute
  '/townhall': typeof TownhallRoute
  '/knowledge-hub/$sopId': typeof KnowledgeHubSopIdRoute
  '/knowledge-hub': typeof KnowledgeHubIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/administration': typeof AdministrationRoute
  '/analytics': typeof AnalyticsRoute
  '/assessments': typeof AssessmentsRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/memos': typeof MemosRoute
  '/notifications': typeof NotificationsRoute
  '/performance-intelligence': typeof PerformanceIntelligenceRoute
  '/qa-coaching': typeof QaCoachingRoute
  '/settings': typeof SettingsRoute
  '/townhall': typeof TownhallRoute
  '/knowledge-hub/$sopId': typeof KnowledgeHubSopIdRoute
  '/knowledge-hub/': typeof KnowledgeHubIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/admin'
    | '/administration'
    | '/analytics'
    | '/assessments'
    | '/leadership'
    | '/login'
    | '/memos'
    | '/notifications'
    | '/performance-intelligence'
    | '/qa-coaching'
    | '/settings'
    | '/townhall'
    | '/knowledge-hub/$sopId'
    | '/knowledge-hub/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/admin'
    | '/administration'
    | '/analytics'
    | '/assessments'
    | '/leadership'
    | '/login'
    | '/memos'
    | '/notifications'
    | '/performance-intelligence'
    | '/qa-coaching'
    | '/settings'
    | '/townhall'
    | '/knowledge-hub/$sopId'
    | '/knowledge-hub'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/admin'
    | '/administration'
    | '/analytics'
    | '/assessments'
    | '/leadership'
    | '/login'
    | '/memos'
    | '/notifications'
    | '/performance-intelligence'
    | '/qa-coaching'
    | '/settings'
    | '/townhall'
    | '/knowledge-hub/$sopId'
    | '/knowledge-hub/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRoute
  AdministrationRoute: typeof AdministrationRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssessmentsRoute: typeof AssessmentsRoute
  LeadershipRoute: typeof LeadershipRoute
  LoginRoute: typeof LoginRoute
  MemosRoute: typeof MemosRoute
  NotificationsRoute: typeof NotificationsRoute
  PerformanceIntelligenceRoute: typeof PerformanceIntelligenceRoute
  QaCoachingRoute: typeof QaCoachingRoute
  SettingsRoute: typeof SettingsRoute
  TownhallRoute: typeof TownhallRoute
  KnowledgeHubSopIdRoute: typeof KnowledgeHubSopIdRoute
  KnowledgeHubIndexRoute: typeof KnowledgeHubIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/townhall': {
      id: '/townhall'
      path: '/townhall'
      fullPath: '/townhall'
      preLoaderRoute: typeof TownhallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-coaching': {
      id: '/qa-coaching'
      path: '/qa-coaching'
      fullPath: '/qa-coaching'
      preLoaderRoute: typeof QaCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance-intelligence': {
      id: '/performance-intelligence'
      path: '/performance-intelligence'
      fullPath: '/performance-intelligence'
      preLoaderRoute: typeof PerformanceIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memos': {
      id: '/memos'
      path: '/memos'
      fullPath: '/memos'
      preLoaderRoute: typeof MemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-hub/': {
      id: '/knowledge-hub/'
      path: '/knowledge-hub'
      fullPath: '/knowledge-hub/'
      preLoaderRoute: typeof KnowledgeHubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-hub/$sopId': {
      id: '/knowledge-hub/$sopId'
      path: '/knowledge-hub/$sopId'
      fullPath: '/knowledge-hub/$sopId'
      preLoaderRoute: typeof KnowledgeHubSopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRoute,
  AdministrationRoute: AdministrationRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssessmentsRoute: AssessmentsRoute,
  LeadershipRoute: LeadershipRoute,
  LoginRoute: LoginRoute,
  MemosRoute: MemosRoute,
  NotificationsRoute: NotificationsRoute,
  PerformanceIntelligenceRoute: PerformanceIntelligenceRoute,
  QaCoachingRoute: QaCoachingRoute,
  SettingsRoute: SettingsRoute,
  TownhallRoute: TownhallRoute,
  KnowledgeHubSopIdRoute: KnowledgeHubSopIdRoute,
  KnowledgeHubIndexRoute: KnowledgeHubIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
